#!/usr/bin/env bash
# Regenerate script/addresses/MainnetAddresses.sol from the newest
# versions/deployment-addresses-mainnet-*.json (or DEPLOYMENT_ADDRESSES_JSON).
# Uses `cast to-check-sum-address` for valid Solidity literals.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

JSON="${DEPLOYMENT_ADDRESSES_JSON:-}"
if [[ -z "$JSON" ]]; then
  JSON="$(ls -t versions/deployment-addresses-mainnet-*.json 2>/dev/null | head -1 || true)"
fi

if [[ -z "$JSON" || ! -f "$JSON" ]]; then
  echo "⚠️  sync-mainnet-addresses-sol: no versions/deployment-addresses-mainnet-*.json (set DEPLOYMENT_ADDRESSES_JSON). Skipping."
  exit 0
fi

if ! command -v jq &>/dev/null; then
  echo "❌ jq is required"
  exit 1
fi

cs() { cast to-check-sum-address "$1" 2>/dev/null || echo "$1"; }

CHAIN_ID=$(jq -r '.chainId' "$JSON")
VERSION=$(jq -r '.version // "unknown"' "$JSON")
CORE=$(cs "$(jq -r '.contracts.Core' "$JSON")")
SD=$(cs "$(jq -r '.contracts.StreamDaemon' "$JSON")")
REG=$(cs "$(jq -r '.contracts.Registry' "$JSON")")
EX=$(cs "$(jq -r '.contracts.Executor' "$JSON")")
UV2=$(cs "$(jq -r '.contracts.UniswapV2Fetcher' "$JSON")")
UV3_100_RAW=$(jq -r '.contracts.UniswapV3Fetcher_0_01 // "0x0000000000000000000000000000000000000000"' "$JSON")
UV3_100=$(cs "$UV3_100_RAW")
UV3_500=$(cs "$(jq -r '.contracts.UniswapV3Fetcher_0_05' "$JSON")")
UV3_3000=$(cs "$(jq -r '.contracts.UniswapV3Fetcher_0_3' "$JSON")")
UV3_10000=$(cs "$(jq -r '.contracts.UniswapV3Fetcher_1' "$JSON")")

OUT="script/addresses/MainnetAddresses.sol"
mkdir -p "$(dirname "$OUT")"

cat >"$OUT" <<EOF
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

/// @notice AUTO-GENERATED by scripts/sync-mainnet-addresses-sol.sh from:
///         $JSON (version $VERSION)
/// @dev     Do not edit by hand. Run: npm run sync:mainnet-addresses:sol
library MainnetAddresses {
    uint256 internal constant CHAIN_ID = $CHAIN_ID;

    address internal constant CORE = $CORE;
    address internal constant STREAM_DAEMON = $SD;
    address internal constant REGISTRY = $REG;
    address internal constant EXECUTOR = $EX;

    address internal constant UNISWAP_V2_FETCHER = $UV2;
    address internal constant UNISWAP_V3_FETCHER_100 = $UV3_100;
    address internal constant UNISWAP_V3_FETCHER_500 = $UV3_500;
    address internal constant UNISWAP_V3_FETCHER_3000 = $UV3_3000;
    address internal constant UNISWAP_V3_FETCHER_10000 = $UV3_10000;
}
EOF

echo "✅ Wrote $OUT from $JSON"
