// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

import "forge-std/Script.sol";
import "forge-std/console.sol";
import "../../../src/Registry.sol";

/**
 * @title DeployRegistryAndConfigureRouters
 * @notice Deploys a new Registry and calls setRouter for each DEX type (same router addresses as ConfigureRouters).
 * @dev Owner = broadcaster. Writes `deployments/phase-b-mainnet.env` with DEPLOY_BAREBONES_REGISTRY.
 */
contract DeployRegistryAndConfigureRouters is Script {
    // Mainnet routers (same as maintenance/ConfigureRouters.s.sol)
    address internal constant UNISWAP_V2_ROUTER = 0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D;
    address internal constant UNISWAP_V3_ROUTER = 0xE592427A0AEce92De3Edee1F18E0157C05861564;
    address internal constant SUSHISWAP_ROUTER = 0xd9e1cE17f2641f24aE83637ab66a2cca9C378B9F;

    // Fetchers used as router targets where applicable (Balancer / CurveMeta)
    address internal constant BALANCER_FETCHER = 0xF9abe8A26EcF289b7e16Ccf88D67252DdA2215A6;
    address internal constant CURVE_FETCHER = 0xdaa78BA8ff44351a7669746209d371bCdD85d062;

    string internal constant OUT_FILE = "deployments/phase-b-mainnet.env";

    function run() external {
        console.log("=== Phase B: Registry deploy + configure routers ===");
        console.log("Chain ID:", block.chainid);

        vm.startBroadcast();

        Registry registry = new Registry();
        address reg = address(registry);
        console.log("New Registry:", reg);

        registry.setRouter("UniswapV2", UNISWAP_V2_ROUTER);
        registry.setRouter("UniswapV3", UNISWAP_V3_ROUTER);
        registry.setRouter("Sushiswap", SUSHISWAP_ROUTER);
        registry.setRouter("BalancerV2", BALANCER_FETCHER);
        registry.setRouter("CurveMeta", CURVE_FETCHER);

        vm.stopBroadcast();

        string memory contents = string.concat(
            "# Generated by DeployRegistryAndConfigureRouters\n",
            "export DEPLOY_BAREBONES_REGISTRY=",
            vm.toString(reg),
            "\n"
        );
        vm.writeFile(OUT_FILE, contents);
        console.log("\nRouters configured. Wrote", OUT_FILE);
        console.log("Next: set DEPLOY_BAREBONES_SALT_TAG (new tag) and run deploy:barebones:core with Phase A+B env sourced.");
    }
}
