// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

import "forge-std/Script.sol";
import "forge-std/console.sol";
import "../../../src/adapters/UniswapV3Fetcher.sol";

/**
 * @title DeployUniswapV3FetchersPhaseA
 * @notice Mainnet: deploy three UniswapV3Fetcher instances (500 / 3000 / 10000) and set QuoterV2 on each.
 * @dev Writes `deployments/phase-a-mainnet.env` with DEPLOY_BAREBONES_V3_* exports for DeployBarebonesCore.
 */
contract DeployUniswapV3FetchersPhaseA is Script {
    /// @dev Uniswap V3 Factory on Ethereum mainnet
    address public constant UNISWAP_V3_FACTORY = 0x1F98431c8aD98523631AE4a59f267346ea31F984;

    /// @dev QuoterV2 on Ethereum mainnet
    address public constant QUOTER_V2 = 0x61fFE014bA17989E743c5F6cB21bF9697530B21e;

    uint24 internal constant FEE_500 = 500;
    uint24 internal constant FEE_3000 = 3000;
    uint24 internal constant FEE_10000 = 10000;

    string internal constant OUT_FILE = "deployments/phase-a-mainnet.env";

    function run() external {
        console.log("=== Phase A: UniswapV3Fetcher x3 + QuoterV2 ===");
        console.log("Chain ID:", block.chainid);
        if (block.chainid != 1) {
            console.log("WARN: not chainid 1 (mainnet); ensure this is intentional.");
        }

        vm.startBroadcast();

        UniswapV3Fetcher f500 = new UniswapV3Fetcher(UNISWAP_V3_FACTORY, FEE_500);
        UniswapV3Fetcher f3000 = new UniswapV3Fetcher(UNISWAP_V3_FACTORY, FEE_3000);
        UniswapV3Fetcher f10000 = new UniswapV3Fetcher(UNISWAP_V3_FACTORY, FEE_10000);

        f500.setQuoterV2(QUOTER_V2);
        f3000.setQuoterV2(QUOTER_V2);
        f10000.setQuoterV2(QUOTER_V2);

        vm.stopBroadcast();

        address a500 = address(f500);
        address a3000 = address(f3000);
        address a10000 = address(f10000);

        console.log("\n--- Deployed (0.05% fee tier / 500):", a500);
        console.log("--- Deployed (0.3% fee tier / 3000):", a3000);
        console.log("--- Deployed (1% fee tier / 10000):", a10000);
        console.log("QuoterV2 on all:", QUOTER_V2);

        string memory contents = string.concat(
            "# Generated by DeployUniswapV3FetchersPhaseA - do not commit if you treat addresses as sensitive\n",
            "export DEPLOY_BAREBONES_V3_500=",
            vm.toString(a500),
            "\n",
            "export DEPLOY_BAREBONES_V3_3000=",
            vm.toString(a3000),
            "\n",
            "export DEPLOY_BAREBONES_V3_10000=",
            vm.toString(a10000),
            "\n"
        );
        vm.writeFile(OUT_FILE, contents);
        console.log("\nWrote", OUT_FILE);
        console.log("Next: Phase B (Registry) or source this file and set DEPLOY_BAREBONES_REGISTRY after Phase B.");
    }
}
