// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

/// @notice AUTO-GENERATED by scripts/sync-mainnet-addresses-sol.sh from:
///         versions/deployment-addresses-mainnet-1.0.9.json (version 1.0.9)
/// @dev     Do not edit by hand. Run: npm run sync:mainnet-addresses:sol
library MainnetAddresses {
    uint256 internal constant CHAIN_ID = 1;

    address internal constant CORE = 0xD0B6DaD2Dc5dad47bEB7C3D7Dd7980a20CD6a710;
    address internal constant STREAM_DAEMON = 0x75C851Ea1f6461f65Fd04582b6E4BF49168632C5;
    address internal constant REGISTRY = 0x34d4bd3D3424B4C06bA14D68a10e1DBA5Cfb11D4;
    address internal constant EXECUTOR = 0xb2194D54cD31A2c23B071ca68394CF9C35910545;

    address internal constant UNISWAP_V2_FETCHER = 0xAFF18eD0314e61F91f7F4F647c4D595f6A59a4c9;
    address internal constant UNISWAP_V3_FETCHER_100 = 0xe3D5dAA0543a396BF14D8404cb9E5Ad19D7eC819;
    address internal constant UNISWAP_V3_FETCHER_500 = 0x15DC9274c61D9B0F20dC09bD0BFA7D1e2D504FC6;
    address internal constant UNISWAP_V3_FETCHER_3000 = 0xD561BC0801Fb9E85Ea151a784fCb41898C98f49a;
    address internal constant UNISWAP_V3_FETCHER_10000 = 0xec5545C87eE4F74d33A4af6F817a1B6eabF67852;
}
