// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

/// @notice AUTO-GENERATED by scripts/sync-mainnet-addresses-sol.sh from:
///         versions/deployment-addresses-mainnet-1.0.8.json (version 1.0.8)
/// @dev     Do not edit by hand. Run: npm run sync:mainnet-addresses:sol
library MainnetAddresses {
    uint256 internal constant CHAIN_ID = 1;

    address internal constant CORE = 0xa017d75FeD4E71799FdE4457191a1E3e295C3b0B;
    address internal constant STREAM_DAEMON = 0xe3A6a07a73727be782b0a7Bc0c093eCB19D0c251;
    address internal constant REGISTRY = 0x34d4bd3D3424B4C06bA14D68a10e1DBA5Cfb11D4;
    address internal constant EXECUTOR = 0xA03762EFF4f98cDA57DeA0a8eB62ab872C832878;

    address internal constant UNISWAP_V2_FETCHER = 0xcDd26C4361AEB4b20f9e5A2119C7aac08B9dA089;
    address internal constant UNISWAP_V3_FETCHER_500 = 0x15DC9274c61D9B0F20dC09bD0BFA7D1e2D504FC6;
    address internal constant UNISWAP_V3_FETCHER_3000 = 0xD561BC0801Fb9E85Ea151a784fCb41898C98f49a;
    address internal constant UNISWAP_V3_FETCHER_10000 = 0xec5545C87eE4F74d33A4af6F817a1B6eabF67852;
}
